"""redesign address fields

Revision ID: 29af9f0a4552
Revises: 991cfbe53146
Create Date: 2026-07-11 08:17:33.987082

"""
from alembic import op
import sqlalchemy as sa


revision = '29af9f0a4552'
down_revision = '991cfbe53146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    address_type_enum = sa.Enum('HOME', 'OFFICE', 'OTHER', name='addresstype')
    address_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('addresses', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('addresses', sa.Column('mobile_number', sa.String(length=15), nullable=False))
    op.add_column('addresses', sa.Column('house_no', sa.String(length=100), nullable=False))
    op.add_column('addresses', sa.Column('street', sa.String(length=255), nullable=False))
    op.add_column('addresses', sa.Column('landmark', sa.String(length=255), nullable=True))
    op.add_column('addresses', sa.Column('address_type', address_type_enum, nullable=False))
    op.drop_column('addresses', 'line1')
    op.drop_column('addresses', 'label')
    op.drop_column('addresses', 'line2')
    # DB-level guarantee (app-level enforcement lives in crud/address.py) that
    # a user can have at most one default address.
    op.create_index(
        'uq_one_default_address_per_user',
        'addresses',
        ['user_id'],
        unique=True,
        postgresql_where=sa.text('is_default = true'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_default_address_per_user', table_name='addresses')
    op.add_column('addresses', sa.Column('line2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('label', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('line1', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('addresses', 'address_type')
    op.drop_column('addresses', 'landmark')
    op.drop_column('addresses', 'street')
    op.drop_column('addresses', 'house_no')
    op.drop_column('addresses', 'mobile_number')
    op.drop_column('addresses', 'full_name')
    sa.Enum(name='addresstype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
