"""add affiliate marketing, influencer coupons, and google auth

Revision ID: 5e475f213dff
Revises: 251fa69ec24c
Create Date: 2026-07-17 20:03:45.120730

"""
from alembic import op
import sqlalchemy as sa


revision = '5e475f213dff'
down_revision = '251fa69ec24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('affiliate_code', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'BLOCKED', name='affiliatestatus'), nullable=False),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliates_affiliate_code'), 'affiliates', ['affiliate_code'], unique=True)
    op.create_index(op.f('ix_affiliates_status'), 'affiliates', ['status'], unique=False)
    op.create_index(op.f('ix_affiliates_user_id'), 'affiliates', ['user_id'], unique=True)
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('affiliate_id', sa.Uuid(), nullable=False),
    sa.Column('landing_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_clicks_affiliate_id'), 'affiliate_clicks', ['affiliate_id'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('AFFILIATE', 'INFLUENCER_COUPON', name='commissionsource'), nullable=False),
    sa.Column('affiliate_id', sa.Uuid(), nullable=True),
    sa.Column('coupon_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('percentage_applied', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EARNED', 'PAID', 'REVERSED', name='commissionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_affiliate_id'), 'commissions', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_commissions_coupon_id'), 'commissions', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_commissions_order_id'), 'commissions', ['order_id'], unique=True)
    op.create_index(op.f('ix_commissions_status'), 'commissions', ['status'], unique=False)
    op.add_column('coupons', sa.Column('is_influencer', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('coupons', 'is_influencer', server_default=None)
    op.add_column('coupons', sa.Column('influencer_name', sa.String(length=255), nullable=True))
    op.add_column('coupons', sa.Column('influencer_commission_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('orders', sa.Column('affiliate_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'orders', 'affiliates', ['affiliate_id'], ['id'])
    op.add_column('payments', sa.Column('affiliate_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'payments', 'affiliates', ['affiliate_id'], ['id'])
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    auth_provider_enum = sa.Enum('LOCAL', 'GOOGLE', name='authprovider')
    auth_provider_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column('auth_provider', auth_provider_enum, nullable=False, server_default='LOCAL'),
    )
    op.alter_column('users', 'auth_provider', server_default=None)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    sa.Enum(name='authprovider').drop(op.get_bind(), checkfirst=True)
    op.drop_column('users', 'google_id')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'affiliate_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'affiliate_id')
    op.drop_column('coupons', 'influencer_commission_percentage')
    op.drop_column('coupons', 'influencer_name')
    op.drop_column('coupons', 'is_influencer')
    op.drop_index(op.f('ix_commissions_status'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_order_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_coupon_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_affiliate_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_affiliate_clicks_affiliate_id'), table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    op.drop_index(op.f('ix_affiliates_user_id'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_status'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_affiliate_code'), table_name='affiliates')
    op.drop_table('affiliates')
    # ### end Alembic commands ###
