"""add site branding table

Revision ID: 7c03dd1c54d7
Revises: 9df3860e30b2
Create Date: 2026-07-19 12:10:22.791978

"""
from alembic import op
import sqlalchemy as sa


revision = '7c03dd1c54d7'
down_revision = '9df3860e30b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_branding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_branding')
    # ### end Alembic commands ###
