"""add cart and wishlist unique constraints

Revision ID: 991cfbe53146
Revises: aa4626c1abe3
Create Date: 2026-07-11 07:05:54.650202

"""
from alembic import op
import sqlalchemy as sa


revision = '991cfbe53146'
down_revision = 'aa4626c1abe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cart_item_product', 'cart_items', ['cart_id', 'product_id'])
    op.create_unique_constraint('uq_wishlist_item_product', 'wishlist_items', ['wishlist_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wishlist_item_product', 'wishlist_items', type_='unique')
    op.drop_constraint('uq_cart_item_product', 'cart_items', type_='unique')
    # ### end Alembic commands ###
