"""add inventory transactions table

Revision ID: 994123bbdb34
Revises: aa33e5669e8b
Create Date: 2026-07-11 12:17:42.094800

"""
from alembic import op
import sqlalchemy as sa


revision = '994123bbdb34'
down_revision = 'aa33e5669e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('movement_type', sa.Enum('ORDER', 'ORDER_CANCELLED', 'MANUAL_INCREASE', 'MANUAL_DECREASE', 'CORRECTION', 'REFUND_RESTOCK', name='movementtype'), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('stock_before', sa.Integer(), nullable=False),
    sa.Column('stock_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_transactions')
    # ### end Alembic commands ###
