"""add order status history and extend order fields

Revision ID: aa33e5669e8b
Revises: b3506d1af614
Create Date: 2026-07-11 09:29:40.905431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'aa33e5669e8b'
down_revision = 'b3506d1af614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # order_status.status reuses the existing `orderstatus` enum type (created
    # by the initial orders migration) — create_type=False stops SQLAlchemy
    # from trying (and failing) to CREATE TYPE a second time.
    order_status_enum = postgresql.ENUM(
        'PENDING', 'CONFIRMED', 'PACKED', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'REFUNDED',
        name='orderstatus', create_type=False,
    )
    op.create_table('order_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('status', order_status_enum, nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order_items', sa.Column('product_name', sa.String(length=255), nullable=False))
    op.add_column('order_items', sa.Column('sku', sa.String(length=50), nullable=False))
    op.add_column('order_items', sa.Column('gst_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('order_items', sa.Column('line_gst', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('order_items', sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('payment_id', sa.Uuid(), nullable=True))
    op.add_column('orders', sa.Column('cancel_reason', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('refund_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('refunded_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'orders', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'refunded_at')
    op.drop_column('orders', 'refund_id')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'cancel_reason')
    op.drop_column('orders', 'payment_id')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['id'])
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('order_items', 'line_total')
    op.drop_column('order_items', 'line_gst')
    op.drop_column('order_items', 'gst_percentage')
    op.drop_column('order_items', 'sku')
    op.drop_column('order_items', 'product_name')
    op.drop_table('order_status_history')
    # ### end Alembic commands ###
