"""add product sku and is_featured

Revision ID: aa4626c1abe3
Revises: 0e60c3de4fdf
Create Date: 2026-07-10 23:58:25.912412

"""
from alembic import op
import sqlalchemy as sa


revision = 'aa4626c1abe3'
down_revision = '0e60c3de4fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
